module.exports = {
    1: ':one:',
    2: ':two:',
    3: ':three:',
    4: ':four:',
    5: ':five:',
    6: ':six:',
    7: ':seven:',
    8: ':eight:',
    9: ':nine:',
    10: ':keycap_ten:',
    A: ':regional_indicator_a:',
    B: ':regional_indicator_b:',
    C: ':regional_indicator_c:',
    D: ':regional_indicator_d:',
    E: ':regional_indicator_e:',
    F: ':regional_indicator_f:',
    G: ':regional_indicator_g:',
    H: ':regional_indicator_h:',
    I: ':regional_indicator_i:',
    J: ':regional_indicator_j:'
}